# This is a basic workflow to help you get started with Actions

name: Upload to PyPi

# Controls when the workflow will run
on:
  # Triggers the workflow when a release is created
  release: 
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up python3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      # Installs and upgrades pip, installs dependencies
      - name: "Installs and upgrades pip, installs dependencies"
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install build deps
          python3 -m pip install setuptools wheel twine
          
      # Build and Upload to PyPI
      - name: Build and Upload to PyPI
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
